Merge prometheus tags into metric tags (fixes #1)
adobe-research/prometheus-opentsdb-exporter pull request #2
Opened 2019-07-16 12:14 UTC by krupenik

2019-07-16 14:00 UTC, andreifecioru requested changes
Please rebase on master (changes in unit-tests should no longer be necessary). Leave only the changes related to the merging of tags.

2019-07-16 14:00 UTC, andreifecioru commented on web/test/MetricsControllerSpec.scala
> +          "test_app_metrics_two{severity=critical,escalation=pagerduty,role=developer} 10",
This was a bug on my side. I fixed that in the latest commit (please take a look). Solving the problem here is fine as a quick fix, but it does not solve the underlying problem (it only masks the problem).

The issue was the way the `MetricsRepoService` is loading the metrics configuration file (the ordering of the files is unpredictable). I fixed that by making sure that the list of files being loaded is sorted alphabetically.

With that fix in place, we can rely in the unit-tests on a predictable/reliable ordering of the metrics which makes these changes unnecessary.

So, my suggestion is to rebase on top of master, drop the changes in the unit-tests and re-submit the PR.

2019-07-16 14:53 UTC, krupenik commented on web/test/MetricsControllerSpec.scala
> +          "test_app_metrics_two{severity=critical,escalation=pagerduty,role=developer} 10",
thanks for the feedback and quick fix. PR rebased and updated.

2019-07-17 13:06 UTC, andreifecioru approved these changes
:ok:

2019-07-17 13:07 UTC, merged